volumes:
  postgres-data:
  redis-data:
  project_api-target:

networks:
  backend:

x-common-env: &common-env
  HOST: "0.0.0.0"
  PORT: 3001 #change port
  REDIS_URL: redis://redis:6379
  DB_TYPE: postgres
  DB_NAME: mairie_360_database
  DB_USER: postgres
  DB_HOST: postgres
  DB_PASSWORD: password
  DB_PORT: 5432

x-depends-on: &depends-on
  postgres:
    condition: service_healthy
  redis:
    condition: service_healthy

x-healthcheck: &healthcheck
  test: ["CMD", "curl", "-f", "http://localhost:3001"] #change port
  interval: 10s
  timeout: 5s
  retries: 5

x-service: &service-template
  image: ghcr.io/mairie360/service_name:latest
  pull_policy: always
  restart: always
  expose:
    - "3001"
  networks:
    - backend
  healthcheck:
    <<: *healthcheck

services:
  postgres:
    image: ghcr.io/mairie360/database:dev-latest
    restart: always
    container_name: mairie360-db-project_api-api #change api name
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: mairie_360_database
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: ghcr.io/mairie360/liquibase-migrations:dev-latest
    container_name: mairie360-liquibase-project_api-api #change api name
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *common-env
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/mairie_360_database
      LIQUIBASE_COMMAND_USERNAME: ${DB_USER:-postgres}
      LIQUIBASE_COMMAND_PASSWORD: ${DB_PASSWORD:-password}
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    command: >
      --changelog-file=changelog.xml
      update
    networks:
      - backend

  redis:
    image: redis:8.4.0-bookworm
    container_name: mairie360-redis-project_api-api #change api name
    restart: always
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  project_api: # change api name
    container_name: project_api-developpement # change api name
    build:
      context: .
      dockerfile: development.Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/project_api/src #change api name
        - action: sync
          path: ./Cargo.toml
          target: /usr/src/project_api/Cargo.toml #change api name
        - action: sync
          path: ./Cargo.lock
          target: /usr/src/project_api/Cargo.lock #change api name
    ports:
      - "3001:3001" #change port
    volumes:
      - project_api-target:/usr/src/project_api/target #change api name
    networks:
      - backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      <<: *common-env
      PUBLIC_URL: http://project.development.mairie360.fr
      JWT_SECRET: b"secret"
      JWT_TIMEOUT: 3600
    depends_on:
      liquibase:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://project_api:3001/health"] # change api name and port
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  nginx:
    image: nginx:1.27.4-bookworm
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      project_api: #change api name
        condition: service_healthy
    extra_hosts:
          - "project_api.development.mairie360.fr:127.0.0.1" # change api name