events {
    worker_connections 1024;
}

http {
    upstream core {
        server project_api.development.mairie360.fr:3001;
    }

    server {
        listen 80;
        server_name development.mairie360.fr;

        location / {
            proxy_pass http://project_api.development.mairie360.fr;
        }
    }
}
