events {
    worker_connections 1024;
}

http {
    # 127.0.0.11 est le résolveur DNS interne par défaut de Docker
    resolver 127.0.0.11 valid=30s;

    upstream project_upstream {
        server project:3001;
    }

    server {
        listen 80;
        server_name development.mairie360.fr;

        location / {
            # On utilise une variable pour que Nginx accepte la config 
            # même si le backend n'est pas résolu instantanément
            set $backend "http://project_upstream";
            proxy_pass $backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}