events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    # On définit une variable pour l'URL du backend
    # Cela empêche le crash au démarrage si project_api n'est pas encore prêt
    server {
        listen 80;
        server_name development.mairie360.fr;

        location / {
            # Utilise le nom exact du service défini dans le docker-compose
            set $backend_host "project_api"; 
            proxy_pass http://$backend_host:3001;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
