name: Project API CI/CD

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: write

jobs:
  APIs-cicd:
    uses: mairie360/CICD/.github/workflows/APIs_cicd.yml@v3.1.1
    permissions:
          contents: write
          packages: write
          id-token: write
    with:
      package_name: project-api
      cicd_version: v3.1.1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      N8N_WEBHOOK_SECRET: ${{ secrets.N8N_WEBHOOK_SECRET }}
